### ISSUE TITLE
README.md - Install Virtuoso section wrong link setting up Virtuoso

### ISSUE THREAD

**Issue by LOBsTerr** [ec-europa/joinup-dev#1090]
## Issue
"setting up Virtuoso" link points to missing module https://github.com/ec-europa/joinup-dev/blob/develop/web/modules/custom/rdf_entity/README.md

## Solution
Provide a proper link how to setup Virtuoso

**Comment by sandervd** [comment]
See PR #1095

**Comment by brummbar** [comment]
Fixed in #1095 . Thanks for reporting @LOBsTerr .
