### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by apastorini** [ec-europa/joinup-dev#1158]
Hello, I try to install joinup-dev.

The versión of software that I have installed are:
PHP 7.0.28 
openjdk version "1.8.0_161"
phing-2.16.1
Archive_Tar      1.4.3   stable
Console_Getopt   1.4.1   stable
PEAR             1.10.5  stable
Structures_Graph 1.1.1   stable
XML_Util         1.4.2   stable
Composer (version 1.6.3)
virtuoso-opensource-7.2.4.2

At the build project step
./vendor/bin/phing build-dev
I dont have the build-dev file
and I cant do this.

Could any help me?
Thanks!

(When I  executed the composer install step
 I got this error:
Fatal error: Uncaught TypeError: Return value of DrupalProject\composer\RemoveWrongPatchedObjects::remove() must be an instance of DrupalProject\composer\void, none returned in /usr/local/bin/joinup-dev/scripts/composer/RemoveWrongPatchedObjects.php:52
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): DrupalProject\composer\RemoveWrongPatchedObjects::remove(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('DrupalProject\\c...', 'remove', Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(322): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#4 phar:///usr/local/bin/composer/src/Composer/Comman in /usr/local/bin/joinup-dev/scripts/composer/RemoveWrongPatchedObjects.php on line 52
)

**Comment by pfrenssen** [comment]
Joinup requires PHP 7.1 at a minimum. You're getting these errors because PHP 7.0 is not yet supporting the `void` return type, this was added in PHP 7.1.

We have this requirement listen in `composer.json` but unfortunately you don't even get to the point of getting the right error message, since Composer is executing code that depends on PHP 7.1.
