### ISSUE TITLE
Taxonomy issue

### ISSUE THREAD

**Issue by cassm199** [ec-europa/joinup-dev#1196]
Hi,

We've deployed JoinUp on our Ubuntu Server environment, however when trying to create a new collection, the policy domain does not return any values, however the Policy Domain taxonomy contains a number of values. With regards to this particular taxonomy, upon trying to edit or deleting any one of the terms, the below error is returned:

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: Graph &#039;draft&#039; doesn&#039;t exist for entity type &#039;taxonomy_term&#039;. in <em class="placeholder">Drupal\rdf_entity\Entity\RdfEntitySparqlStorage-&gt;Drupal\rdf_entity\Entity\{closure}()</em> (line <em class="placeholder">1264</em> of <em class="placeholder">modules/contrib/rdf_entity/src/Entity/RdfEntitySparqlStorage.php</em>). 

These are the specs:

Drupal: 8.5.3
Ubuntu :16
PHP: 7.1
Database: MySQL

**Comment by sandervd** [comment]
Hi @cassm199,

Indeed, the policy domain taxonomy has been populated during the migration of Joinup from Drupal 6 to Drupal 8. Could you try the following:
- Extract the policy domain file into resources/fixtures
[policy_domain.rdf.zip](https://github.com/ec-europa/joinup-dev/files/2026898/policy_domain.rdf.zip)
- Run the phing target 'import-rdf-fixtures'
./vendor/bin/phing import-rdf-fixtures

This should populate the policy domain taxonomy with the terms of Joinup.

**Comment by cassm199** [comment]
Hi @sandervd 

Thanks for your prompt reply. I've tried your suggestion however to no avail. The Policy Domains terms were still not visible. I've outputted the results from the phing import-rdf-fixtures command and no errors were thrown.

`Buildfile: /var/www/joinup-dev/build.xml
   [import] Unable to find build file: /var/www/joinup-dev/build.local.xml... skipped
     [echo] Loading AWS additional tasks.
     [echo] Turn environment variable into a phing property
     [echo] Loading infra additional tasks.
 [property] Loading /var/www/joinup-dev/build.properties.local
 [property] Loading /var/www/joinup-dev/build.properties
 [property] Loading /var/www/joinup-dev/build.properties.dist
     [echo] Loading Behat task.
     [echo] Loading After Import RDF fixtures task.
     [echo] Setting-up MySQL auto-increment values for {comment}, {file_managed}, {node} and {users}.
     [echo] Loading Amazon S3 download task.
     [echo] Loading Amazon S3 list task.
     [echo] Loading Truncate Cache Tables task.
     [echo] Loading Empty MySQL Database task.
     [echo] Loading Drush task.
     [echo] Loading PHP Codesniffer Configuration task.
     [echo] Loading PHPUnit Configuration task.
 [property] Loading /var/www/joinup-dev/build.properties.local
 [property] Loading /var/www/joinup-dev/build.properties
 [property] Loading /var/www/joinup-dev/build.properties.dist

My Drupal Project > import-rdf-fixtures:

[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://adms-sw-v1.00>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 11 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://adms_skos_v1.00>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 1 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://eira_skos>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 3 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://actor>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 1 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://business-process>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 2 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://countries-skos>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 10 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://data-theme-skos>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 2 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://filetypes-skos>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 5 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://languages-skos>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 956 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://policy_domain>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 73 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://product_type>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 249 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://solution_category>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 1 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://standardization_level>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 1 msec.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Executing: echo 'SPARQL CLEAR GRAPH <http://test_resource_type>;' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[rdf-import-fixtures] Connected to OpenLink Virtuoso
[rdf-import-fixtures] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[rdf-import-fixtures] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[rdf-import-fixtures] Type HELP; for help and EXIT; to exit.
[rdf-import-fixtures] SQL>
[rdf-import-fixtures] Done. -- 1 msec.
[rdf-import-fixtures] SQL>
[afterrdffixturesimport] Executing: echo 'sparql DELETE FROM <http://languages-skos> { ?entity ?field ?value. } WHERE { ?entity ?field ?value . FILTER(str(?value) = "Multilingual Code") };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 215 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql INSERT INTO <http://adms-sw-v1.00> { <http://purl.org/adms/licencetype/ViralEffect-ShareAlike>  <http://www.w3.org/2004/02/skos/core#inScheme> <http://purl.org/adms/licencetype/1.1> };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 1 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql DELETE FROM <http://adms_skos_v1.00> { ?entity ?field ?value. } WHERE { ?entity ?field ?value . ?entity <http://www.w3.org/2004/02/skos/core#inScheme> <http://purl.org/adms/licencetype/1.0>};' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 4 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql DELETE { GRAPH ?g { ?entity ?field ?value } } WHERE { GRAPH ?g { ?entity ?field ?value . FILTER (LANG(?value) != "" && LANG(?value) != "en") } };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 881 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql INSERT INTO <http://eira_skos> { ?subject a skos:Concept . ?subject skos:topConceptOf <http://data.europa.eu/eira> } WHERE { ?subject a skos:Collection . };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 3 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql INSERT INTO <http://eira_skos> { ?subject skos:topConceptOf <http://data.europa.eu/eira> } WHERE { GRAPH <http://eira_skos> { ?subject a skos:Concept .} };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 4 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql INSERT INTO <http://eira_skos> { ?member skos:broaderTransitive ?collection } WHERE { ?collection a skos:Collection . ?collection skos:member ?member };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 5 msec.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Executing: echo 'sparql DELETE FROM <http://countries-skos> { ?entity ?field ?value. } WHERE { ?entity ?field ?value . ?entity <http://publications.europa.eu/ontology/authority/end.use> ?date . FILTER ( bound(?date) ) };' | /usr/local/virtuoso-opensource/bin/isql 'localhost' 'dba' 'dba'
[afterrdffixturesimport] Connected to OpenLink Virtuoso
[afterrdffixturesimport] Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
[afterrdffixturesimport] OpenLink Interactive SQL (Virtuoso), version 0.9849b.
[afterrdffixturesimport] Type HELP; for help and EXIT; to exit.
[afterrdffixturesimport] SQL>
[afterrdffixturesimport] Done. -- 7 msec.
[afterrdffixturesimport] SQL>

BUILD FINISHED

Total time: 5.4206 seconds

`

**Comment by sandervd** [comment]
Hi @cassm199,

I managed to reproduce the issue on our end, and created an issue in our sprint. I'll keep you posted.

**Comment by idimopoulos** [comment]
@cassm199, #1202 is merged into develop. The issues with CRUD operations on Policy Domain terms should be fixed now.
