### ISSUE TITLE
provide RSS/ATOM feeds

### ISSUE THREAD

**Issue by schiessle** [ec-europa/joinup-dev#1467]
On the old joinup page I could subscribe to RSS feeds to stay up-to-date. Would be great if this would be possible with the new joinup as well.

**Comment by brummbar** [comment]
Hello @schiessle, this functionality is under development right now and it will be soon available.

**Comment by schiessle** [comment]
@brummbar do you know when we will be able to use it at https://joinup.ec.europa.eu ?
