### ISSUE TITLE
joinup_theme missing dependency yields an error

### ISSUE THREAD

**Issue by kalinchernev** [ec-europa/joinup-dev#168]
When using the theme on clean Drupal install, the following error occurs:

```
Symfony\Component\Routing\Exception\RouteNotFoundException: Route "view.search.page_1" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 187 of /home/ubuntu/workspace/web/core/lib/Drupal/Core/Routing/RouteProvider.php).
```

There are some missing dependencies:
```
Searching for view.search.page_1 in /web/themes/custom/joinup  (Found 2 matches in 2 files)

/web/themes/custom/joinup/templates/parts/featured--anonymous.html.twig:
	22:           <form action="{{ path("view.search.page_1") }}">

/web/themes/custom/joinup/templates/parts/header.html.twig:
	18:       <form action="{{ path("view.search.page_1") }}" class="search-bar__input-container mdl-textfield__expandable-holder">

Found 2 matches in 2 files 
```

**Comment by idimopoulos** [comment]
@kalinchernev, this dependency comes from a module in our project.
The thing is that we do not have a base theme and a sub theme and it is being built in a project specific notion.
Thus said, it is not supposed to work on a clean setup.
Still, If you want to test it in a clean setup, you can remove all occurrences of this dependency (remove the whole form element) and it should work.

**Comment by kalinchernev** [comment]
@idimopoulos, sure, closing then.
Indeed removing these was ok :)
